#!/usr/bin/env bash
#this script displays 1 to 20 and a different in line 4 9 and 17
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    count=$((count + 1))
done
