#!/usr/bin/env bash
#this script displays 1 to 20 and a different in line 4 9 and 17
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo "Best School"
            ;;
    esac
    count=$((count + 1))
done
