#!/usr/bin/env bash
# this script that displays the time for 12 hours and 59 minutes

hour=0

while [[ $hour -le 23 ]]; do
    echo "Hour: $hour"
    minute=0

    while [[ $minute -le 59 ]]; do
        echo $minute
        ((minute++))
    done

    ((hour++))
done

